#!/bin/bash

NAME="ttt";

build () {
    javac *.java && \
        jar cvfm ${NAME}.jar manifest.txt *.class;
}

clean () {
    rm *.class
}

run () {
    java -jar ${NAME}.jar
}

if [ "$1" == "build" ]
then
    build;
elif [ "$1" == "run" ]
then
    build && run;
elif [ "$1" == "clean" ]
then
    clean;
fi
